repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: debug-statements
      -   id: check-yaml
      -   id: check-json
      -   id: check-merge-conflict
      -   id: pretty-format-json
          args: ['--autofix']
      -   id: check-added-large-files
      -   id: debug-statements
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.6
      hooks:
        - id: reorder-python-imports
  -   repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
        - id: black
          language_version: python3.9
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
        - id: flake8
          additional_dependencies: [flake8-bugbear]
          args: [--ignore, 'B008,W503,E501,E731,W504,E203', --exclude, '.git, deployments']
