name: Python Code Checks

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Format with Black
        run: |
          black --diff --check .
      - name: Lint with flake8
        run: |
          flake8 . --ignore 'B008,W503,E501,E731,W504,E203' --show-source --statistics
